site_name: Python guide for R users
site_url: https://CalHenry.github.io/Python-guide-for-R-users
repo_url: https://github.com/CalHenry/Python-guide-for-R-users

# theme related ------
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy

markdown_extensions:
  - tables:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.superfences          # code blocks inside admonitions etc.
  - pymdownx.blocks.admonition:    # callouts
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - example
      - important
      - quote
  - pymdownx.mark
  - pymdownx.details
  - attr_list
  - pymdownx.extra

extra_css:
  - css/extra.css
