[project]
site_name = "Python guide for R users"
site_url = "https://CalHenry.github.io/Python-guide-for-R-users"
repo_url = "https://github.com/CalHenry/Python-guide-for-R-users"
repo_name = "CalHenry/Python-guide-for-R-users"
site_author = "Calixte Henry"

extra_css = ["css/extra.css"]

nav = [
  "index.md",
  "terminal.md",
  "python.md",
  "git.md",
  "coder_python.md",
  "notebooks.md",
  "toolkit.md"
]

[project.theme]
#variant = "classic"

features = [
    #"navigation.tabs",
    "navigation.top",
    "content.code.copy"
]

# Palette toggle for system (auto)
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "amber"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to light mode"

# Markdown extensions
[project.markdown_extensions.tables]
[project.markdown_extensions.attr_list]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true

[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.extra]

[project.markdown_extensions.pymdownx.blocks.admonition]
types = [
    "new",
    "settings",
    "note",
    "abstract",
    "info",
    "tip",
    "success",
    "question",
    "warning",
    "example",
    "quote"
]
